# Generated by Django 5.0.1 on 2024-01-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questmodel',
            name='op4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
